global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.EntityFrameworkCore.Migrations;
global using System;
global using Poseidon.DAL.Core;
global using Poseidon.DAL.Entities;
global using Poseidon.DAL.Repositories.Interfaces;